package YasserBlog::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'YasserBlog::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:CatalystBlog',
        user => 'yasser',
        password => '',
        AutoCommit => q{1},
    }
);

=head1 NAME

YasserBlog::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<YasserBlog>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<YasserBlog::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Yasser

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
